# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftGroupFinalProject' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireNetworkActivityIndicator'

  # Pods for SwiftGroupFinalProject

  target 'SwiftGroupFinalProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftGroupFinalProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
